<?php
session_start();
$lock=__DIR__.'/config/installed.lock';
if(file_exists($lock)){http_response_code(403);die('<meta charset="utf-8"><body dir="rtl" style="font-family:Tahoma;padding:40px"><h2>السكربت مثبت مسبقاً</h2><p>لإعادة التثبيت احذف الملف <code>config/installed.lock</code> يدوياً.</p><a href="login.php">الذهاب لتسجيل الدخول</a><div style="text-align:center;color:#7b8799;font:12px Tajawal,Tahoma;margin:24px 0">جميع حقوق التطوير والتصميم : <b>محمد القرعان</b><div class="social-icons"><a class="social-icon" href="https://www.facebook.com/elqdes" target="_blank" rel="noopener" aria-label="Facebook @elqdes"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.6 22v-9h3l.45-3.5H13.6V7.25c0-1.01.28-1.7 1.73-1.7h1.87V2.42c-.32-.04-1.43-.14-2.72-.14-2.69 0-4.53 1.64-4.53 4.66V9.5H6.9V13h3.05v9z"/></svg></a><a class="social-icon" href="https://www.instagram.com/elqdes/" target="_blank" rel="noopener" aria-label="Instagram @elqdes"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7zm5 3a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm5.6-3.5a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4z"/></svg></a></div></div></body>');}
$err='';$ok=false;$api='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $host=trim($_POST['db_host']??'localhost');$name=trim($_POST['db_name']??'');$user=trim($_POST['db_user']??'');$pass=$_POST['db_pass']??'';
  $admin=trim($_POST['admin_user']??'admin');$adminPass=$_POST['admin_pass']??'';
  try{
    if(!$name||!$user||strlen($adminPass)<8) throw new Exception('تأكد من بيانات قاعدة البيانات، وكلمة مرور المدير يجب أن تكون 8 أحرف على الأقل.');
    $pdo=new PDO("mysql:host=$host;dbname=$name;charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
    $sql=file_get_contents(__DIR__.'/install.sql');
    foreach(array_filter(array_map('trim',preg_split('/;\s*(?:\r?\n|$)/',$sql))) as $statement){ if(stripos($statement,'--')===0){$statement=preg_replace('/^(?:--[^\n]*\n)+/','',$statement);} if(trim($statement)!=='')$pdo->exec($statement); }
    $api=bin2hex(random_bytes(24));$hash=password_hash($adminPass,PASSWORD_DEFAULT);
    $st=$pdo->prepare('INSERT INTO api_keys(key_name,api_key,is_active) VALUES(?,?,1)');$st->execute(['المفتاح الرئيسي',$api]);
    $pdo->prepare("INSERT INTO settings(setting_key,setting_value) VALUES('version','5.0') ON DUPLICATE KEY UPDATE setting_value='5.0'")->execute();
    $cfg="<?php\nreturn ".var_export(['db_host'=>$host,'db_name'=>$name,'db_user'=>$user,'db_pass'=>$pass,'admin_user'=>$admin,'admin_pass_hash'=>$hash,'api_key'=>$api],true).";\n";
    if(file_put_contents(__DIR__.'/config/config.php',$cfg,LOCK_EX)===false) throw new Exception('تعذر كتابة config/config.php. تأكد من صلاحيات المجلد.');
    file_put_contents($lock,date('c'));
    $ok=true;
  }catch(Throwable $e){$err=$e->getMessage();}
}
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>تثبيت NotifyBridge</title><link rel="stylesheet" href="assets/style.css"></head><body><main class="installer"><h1>🔔 NotifyBridge V5.0</h1><p>معالج التثبيت</p><?php if($err):?><div class="err"><?=htmlspecialchars($err)?></div><?php endif?><?php if($ok):?><div class="success"><h2>تم التثبيت بنجاح ✅</h2><p>رابط الاستقبال الذي ستضعه في تطبيق الهاتف:</p><code id="push"><?php $scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$base=rtrim(dirname($_SERVER['SCRIPT_NAME']),'/\\');echo htmlspecialchars($scheme.'://'.$_SERVER['HTTP_HOST'].$base.'/api/push.php');?></code><p>API Key:</p><code><?=htmlspecialchars($api)?></code><p><b>احتفظ بالمفتاح في مكان آمن.</b></p><a class="btn" href="login.php">دخول لوحة التحكم</a></div><?php else:?><form method="post"><h3>قاعدة البيانات</h3><input name="db_host" value="localhost" placeholder="DB Host" required><input name="db_name" placeholder="اسم قاعدة البيانات" required><input name="db_user" placeholder="مستخدم قاعدة البيانات" required><input name="db_pass" type="password" placeholder="كلمة مرور قاعدة البيانات"><h3>حساب المدير</h3><input name="admin_user" value="admin" placeholder="اسم المستخدم" required><input name="admin_pass" type="password" minlength="8" placeholder="كلمة مرور قوية (8 أحرف على الأقل)" required><button>تثبيت السكربت</button></form><?php endif?></main><div style="text-align:center;color:#7b8799;font:12px Tajawal,Tahoma;margin:24px 0">جميع حقوق التطوير والتصميم : <b>محمد القرعان</b><div class="social-icons"><a class="social-icon" href="https://www.facebook.com/elqdes" target="_blank" rel="noopener" aria-label="Facebook @elqdes"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.6 22v-9h3l.45-3.5H13.6V7.25c0-1.01.28-1.7 1.73-1.7h1.87V2.42c-.32-.04-1.43-.14-2.72-.14-2.69 0-4.53 1.64-4.53 4.66V9.5H6.9V13h3.05v9z"/></svg></a><a class="social-icon" href="https://www.instagram.com/elqdes/" target="_blank" rel="noopener" aria-label="Instagram @elqdes"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7zm5 3a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm5.6-3.5a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4z"/></svg></a></div></div></body></html>
